#  Server容器配置
server:
  port: 80

spring:
  session:
    store-type: redis
  application:
    name: backend-manage
  datasource:
    name: 主库
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/backend?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: Chen1436863821.
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: Chen1436863821.
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    locale: zh_CN
  main:
    #  可以重写默认的bean定义
    allow-bean-definition-overriding: true

#  属性加密配置
jasypt:
  encryptor:
    password: ${env_jasypt_encryptor_password}
    algorithm: PBEWithMD5AndDES
    keyObtentionIterations: 1000
    poolSize: 1
    saltGeneratorClassname: org.jasypt.salt.RandomSaltGenerator
    stringOutputType: base64

swagger:
  enable: true

logging:
  level:
    com.chenfangming.backend.manage.persistence.mapper: debug