server:
  port: 80

spring:
  # 数据库配置
  datasource:
    name: 主库
    url: jdbc:mysql://127.0.0.1:3306/backend?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: chen1436863821
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_null


## MyBatis配置
#mybatis:
#  mapper-locations: classpath*:com/chenfangming/backend/core/persistence/mapper/*Mapper.xml



