#  Server容器配置
server:
  port: 80

spring:
  application:
    name: backend-manage
  datasource:
    url: ENC(YccvdM3ifnDfUQ7cd3s8s3LgrSw47j5ZuDa3cjPVe1WI4JDNyUTAmLoOQXZfWSaQQ18aZHcCMkPCuYLfg/5wmBXEyEIHYfwf6mjhYaWHZUjxXjYGOSQz2P7dNXfjrkNUo6RRvosIU0TXQHWLaCwww74/T5xI/WLxPULVhoQW/8dPmpGUeCDqB0TVwuqE7Xcp)
    username: ENC(zmoxH916yXreU/MPmieDSA==)
    password: ENC(4Rmcj22oVnyJAkQTfCurue86DixKlEeW)
  security:
    user:
      name: admin
      password: admin


#  属性加密配置
jasypt:
  encryptor:
    password:

swagger:
  enable: true

mybatis-plus:
  global-config:
    refresh: true
