# 环境 开发dev|测试test|生产pro
spring:
  profiles:
    active: @env@
  # 数据库配置
  datasource:
    name: 主库
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_null